"use client";

import { ThemeProvider } from "@/components/MaterialTailwind/MaterialTailwind";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";

import NavBarT from "@/components/MaterialTailwind/NavBar/NavBar";
import SideBarT from "@/components/MaterialTailwind/SideBar/SideBar";

const inter = Inter({ subsets: ["latin"] });
import "./globals.css";
import Footer from "@/components/MaterialTailwind/Footer/Footer";

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const path = usePathname();

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          {path !== "/" && (
            <>
              <NavBarT />
              <div className="flex flex-row w-full">
                <SideBarT />
                <div className="ml-[220px] w-full">
                  {children}
                  <Footer />
                </div>
              </div>
            </>
          )}
          {path === "/" && (
            <>
              {children}
              <Footer />
            </>
          )}
        </ThemeProvider>
      </body>
    </html>
  );
}
